### ISSUE TITLE
Is it still accurate that Let's Encrypt doesn't allow wildcard domains?

### ISSUE THREAD

**Issue by jamauro** [meteor/galaxy-docs#173]
From https://galaxy-guide.meteor.com/encryption.html#lets-encrypt:
```
Let's Encrypt certificates are not available for wildcard (*.) domains.
```

Looks like Let's Encrypt added this ability earlier this year: https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

Is it possible with Galaxy?

**Comment by glasser** [comment]
That's true. However, Let's Encrypt only supports granting wildcard certificates based on a DNS challenge, and Galaxy only implements the HTTP challenge.  In order for Galaxy to request and renew wildcard certificates for you with a DNS challenge, you would have to give Galaxy the ability to manage your domain's DNS registration, which generally works differently for every DNS provider.  Because of this, we haven't prioritized figuring out a way to get this to work.

I've updated the docs to clarify the situation. Thanks for the suggestion!
