### ISSUE TITLE
Link to kadira.io academy in the docs is broken 

### ISSUE THREAD

**Issue by OlivierJM** [meteor/galaxy-docs#209]
the reference link here https://galaxy-guide.meteor.com/apm-make-your-app-faster.html is broken it goes to this page https://kadira.io/academy/meteor-performance-101

**Comment by paulocsanz** [comment]
The same is true for https://galaxy-guide.meteor.com/apm-reducing-pubsub-data-usage.html The last link named "Network Latency" points to kadira.

Kadira is no more. Most projects are moving to something like Prometheus + Grafana, for example: RocketChat/Rocket.Chat#5730. But it has been a few years already.

Are there plans to integrate another metrics monitor meteor?

**Comment by paulocsanz** [comment]
It's also broken here: https://galaxy-guide.meteor.com/apm-optimize-your-app-for-oplog.html

Are there other ways to monitor queries in production for their oplog usage? Does Meteor APM still support that, or not since kadira is offline?

**Comment by OlivierJM** [comment]
cc: @filipenevola

**Comment by filipenevola** [comment]
Hi @paulocsanz and @OlivierJM Kadira was [acquired by MDG](https://blog.meteor.com/mdg-acquires-kadira-apm-96dfb3167fe5) in the past and it is know offered in the Professional plan of Meteor cloud under the new name "Meteor APM".

You can check more about Cloud here:
https://www.meteor.com/cloud

BTW, I already removed the old links to Kadira, they were just a reference because the content was already copied into the Guide.
